[project]
name = "project2-realtimevideoagent"
version = "0.1.0"
description = "Real Time Video Analysis Agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ultralytics>=8.4.0",
]
